title: Drain Gang CSA Github Pages
markdown: kramdown
url: ""
baseurl: "/drain-jekyll"

# for atom feed
author:
  name: Drain Gang
  email: piraadwan@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
